/**
 * Scenario Definitions
 *
 * Concrete practice scenarios for common Git tasks.
 */

import { ScenarioDefinition, ScenarioType } from './types';

export const SCENARIO_FIRST_COMMIT: ScenarioDefinition = {
  id: 'scenario-first-commit',
  type: ScenarioType.FirstCommit,
  title: 'Your First Commit',
  description: 'Learn to make your first commit by creating a file and capturing a snapshot of your work.',
  difficulty: 'beginner',
  estimatedMinutes: 10,
  steps: [
    {
      id: 'first-commit-1',
      order: 1,
      title: 'Open a Repository',
      instruction: 'Navigate to the Repository Grove and open or create a test repository.',
      orchardMetaphor: 'Find your plot of land where your tree will grow.',
      hint: 'If you don\'t have a repository yet, create a new one in an empty folder.',
      canSkip: false,
    },
    {
      id: 'first-commit-2',
      order: 2,
      title: 'Create a New File',
      instruction: 'Create a new file named "hello.txt" in your repository folder with some text inside.',
      orchardMetaphor: 'Plant a seed - add something new to your garden.',
      expectedAction: 'create file',
      validation: {
        type: 'file-exists',
        params: { fileName: 'hello.txt' },
      },
      hint: 'Use any text editor to create a file. Even "Hello World!" is perfect.',
      canSkip: true,
    },
    {
      id: 'first-commit-3',
      order: 3,
      title: 'Stage the File',
      instruction: 'In the Git Operations panel, click the "+" button next to your new file to stage it.',
      orchardMetaphor: 'Prepare the soil around your new seed.',
      expectedAction: 'git add',
      hint: 'Staging tells Git which changes you want to include in your next commit.',
      canSkip: false,
    },
    {
      id: 'first-commit-4',
      order: 4,
      title: 'Write a Commit Message',
      instruction: 'In the commit message box, write "Add hello.txt" or a similar message describing what you did.',
      orchardMetaphor: 'Write a note in your gardening journal about what you planted.',
      hint: 'Good commit messages are short but descriptive. They explain WHAT you did.',
      canSkip: false,
    },
    {
      id: 'first-commit-5',
      order: 5,
      title: 'Make the Commit',
      instruction: 'Click the "Commit" button to create your first commit!',
      orchardMetaphor: 'Add a growth ring to your tree - a permanent record of this moment.',
      expectedAction: 'git commit',
      validation: {
        type: 'commit-made',
      },
      canSkip: false,
    },
  ],
  reward: {
    achievement: 'first-commit',
    description: 'You\'ve made your first commit! Your tree has begun to grow. 🌱',
  },
  relatedQuests: ['quest-making-changes-first-commit'],
};

export const SCENARIO_CREATE_BRANCH: ScenarioDefinition = {
  id: 'scenario-create-branch',
  type: ScenarioType.Branching,
  title: 'Growing Your First Branch',
  description: 'Learn to create and switch to a new branch for experimental work.',
  difficulty: 'beginner',
  estimatedMinutes: 8,
  prerequisites: ['scenario-first-commit'],
  steps: [
    {
      id: 'branch-1',
      order: 1,
      title: 'Open Branch Manager',
      instruction: 'In your repository view, navigate to the Branch Manager section.',
      orchardMetaphor: 'Visit the part of your orchard where you tend to limbs.',
      hint: 'The Branch Manager shows all your branches and lets you create new ones.',
      canSkip: false,
    },
    {
      id: 'branch-2',
      order: 2,
      title: 'Click "Grow Limb"',
      instruction: 'Click the "Grow Limb" button to start creating a new branch.',
      orchardMetaphor: 'Prepare to grow a new limb on your tree.',
      canSkip: false,
    },
    {
      id: 'branch-3',
      order: 3,
      title: 'Name Your Branch',
      instruction: 'Enter a descriptive name like "feature-test" or "experiment-1".',
      orchardMetaphor: 'Give your new limb a name so you can identify it later.',
      hint: 'Use lowercase with hyphens. Avoid spaces or special characters.',
      canSkip: false,
    },
    {
      id: 'branch-4',
      order: 4,
      title: 'Create the Branch',
      instruction: 'Confirm creation. Your new branch is created from your current position.',
      orchardMetaphor: 'The new limb sprouts from where you are standing on the tree.',
      expectedAction: 'git branch',
      validation: {
        type: 'branch-created',
      },
      canSkip: false,
    },
    {
      id: 'branch-5',
      order: 5,
      title: 'Switch to New Branch',
      instruction: 'Click "Walk to Limb" to switch to your newly created branch.',
      orchardMetaphor: 'Walk along your tree to this new limb.',
      expectedAction: 'git checkout',
      validation: {
        type: 'branch-switched',
      },
      canSkip: false,
    },
  ],
  reward: {
    achievement: 'first-branch',
    description: 'You\'ve grown and switched to your first branch! Now you can experiment freely. 🌿',
  },
  relatedQuests: ['quest-branches-creating-branches'],
};

export const SCENARIO_MERGE_BRANCH: ScenarioDefinition = {
  id: 'scenario-merge-branch',
  type: ScenarioType.Merging,
  title: 'Grafting Branches Together',
  description: 'Learn to merge one branch into another, combining work from different lines of development.',
  difficulty: 'intermediate',
  estimatedMinutes: 12,
  prerequisites: ['scenario-create-branch'],
  steps: [
    {
      id: 'merge-1',
      order: 1,
      title: 'Understand Current State',
      instruction: 'Make sure you have at least two branches: main and a feature branch with some commits.',
      orchardMetaphor: 'Check that you have two limbs ready to graft together.',
      hint: 'If you need to, create a branch and make a commit on it first.',
      canSkip: true,
    },
    {
      id: 'merge-2',
      order: 2,
      title: 'Switch to Target Branch',
      instruction: 'Switch to the branch you want to merge INTO (usually "main" or "master").',
      orchardMetaphor: 'Walk to the limb where you want to attach the other branch.',
      expectedAction: 'git checkout',
      hint: 'You merge FROM a feature branch INTO main, so be on main first.',
      canSkip: false,
    },
    {
      id: 'merge-3',
      order: 3,
      title: 'Initiate Merge',
      instruction: 'Use the merge option in Branch Manager to merge your feature branch.',
      orchardMetaphor: 'Begin the grafting process - joining two limbs into one.',
      expectedAction: 'git merge',
      hint: 'Select the branch you want to bring in, then confirm the merge.',
      canSkip: false,
    },
    {
      id: 'merge-4',
      order: 4,
      title: 'Verify Merge',
      instruction: 'Check that the changes from your feature branch now appear in main.',
      orchardMetaphor: 'Inspect the graft - the growth from both limbs is now unified.',
      hint: 'Look at your commit history to see commits from both branches.',
      canSkip: true,
    },
    {
      id: 'merge-5',
      order: 5,
      title: 'Clean Up (Optional)',
      instruction: 'You can now delete the feature branch since its work is merged.',
      orchardMetaphor: 'Prune the old limb now that its growth is part of the trunk.',
      hint: 'Use "Prune Limb" in Branch Manager. This is optional but keeps things tidy.',
      canSkip: true,
    },
  ],
  reward: {
    achievement: 'first-merge',
    description: 'You\'ve successfully merged branches! You can now combine work from different paths. 🌳',
  },
  relatedQuests: ['quest-branches-merging-branches'],
};

export const SCENARIO_FIX_MISTAKE: ScenarioDefinition = {
  id: 'scenario-fix-mistake',
  type: ScenarioType.Undoing,
  title: 'Pruning Mistakes',
  description: 'Learn to safely undo changes and correct mistakes without losing important work.',
  difficulty: 'intermediate',
  estimatedMinutes: 10,
  steps: [
    {
      id: 'undo-1',
      order: 1,
      title: 'Make a Change',
      instruction: 'Edit an existing file in your repository but DON\'T commit it yet.',
      orchardMetaphor: 'Try a small experimental trim on a branch.',
      hint: 'Open any file, add some text, and save. This simulates a mistake.',
      canSkip: true,
    },
    {
      id: 'undo-2',
      order: 2,
      title: 'Realize the Mistake',
      instruction: 'Imagine you didn\'t mean to make that change. You want your file back as it was.',
      orchardMetaphor: 'Decide that the trim wasn\'t quite right.',
      canSkip: true,
    },
    {
      id: 'undo-3',
      order: 3,
      title: 'Discard Changes',
      instruction: 'In Git Operations, find the modified file and use "discard changes" or unstage it.',
      orchardMetaphor: 'Grow the trimmed part back to how it was before.',
      expectedAction: 'git restore',
      hint: 'Discarding changes removes uncommitted modifications. The file returns to its last committed state.',
      canSkip: false,
    },
    {
      id: 'undo-4',
      order: 4,
      title: 'Verify Restoration',
      instruction: 'Open the file and confirm it\'s back to its previous state.',
      orchardMetaphor: 'Check that the branch looks just as it did before your experimental trim.',
      canSkip: true,
    },
  ],
  reward: {
    achievement: 'safe-undo',
    description: 'You\'ve learned to safely undo mistakes! Your garden is resilient. 🌿',
  },
  relatedQuests: ['quest-advanced-undoing-changes'],
};

export const SCENARIO_STASH_WORK: ScenarioDefinition = {
  id: 'scenario-stash-work',
  type: ScenarioType.Stashing,
  title: 'Storing Seeds in the Nursery',
  description: 'Learn to temporarily set aside unfinished work using Git stash.',
  difficulty: 'intermediate',
  estimatedMinutes: 10,
  steps: [
    {
      id: 'stash-1',
      order: 1,
      title: 'Start Some Work',
      instruction: 'Make changes to files but don\'t commit them. Leave them in a work-in-progress state.',
      orchardMetaphor: 'Start planting some seeds, but don\'t finish.',
      hint: 'Edit a file and save, but don\'t stage or commit.',
      canSkip: true,
    },
    {
      id: 'stash-2',
      order: 2,
      title: 'Urgent Task Appears',
      instruction: 'Imagine you need to switch branches urgently, but don\'t want to commit half-done work.',
      orchardMetaphor: 'You need to work on a different part of the orchard right away.',
      canSkip: true,
    },
    {
      id: 'stash-3',
      order: 3,
      title: 'Stash Your Changes',
      instruction: 'Use the stash feature to temporarily save your work without committing.',
      orchardMetaphor: 'Move your unfinished seeds to a safe nursery bed.',
      expectedAction: 'git stash',
      hint: 'Stash saves your changes and returns your working directory to a clean state.',
      canSkip: false,
    },
    {
      id: 'stash-4',
      order: 4,
      title: 'Do Other Work',
      instruction: 'Your working directory is now clean. You could switch branches or do other work.',
      orchardMetaphor: 'Work on other parts of your orchard freely.',
      canSkip: true,
    },
    {
      id: 'stash-5',
      order: 5,
      title: 'Restore Stashed Work',
      instruction: 'When ready, restore your stashed changes to continue where you left off.',
      orchardMetaphor: 'Bring your seeds back from the nursery to continue planting.',
      expectedAction: 'git stash pop',
      hint: 'Stash pop retrieves your saved changes and applies them back to your working directory.',
      canSkip: false,
    },
  ],
  reward: {
    achievement: 'stash-master',
    description: 'You\'ve mastered stashing! You can now juggle multiple tasks gracefully. 🌱',
  },
  relatedQuests: ['quest-advanced-stashing'],
};

export const ALL_SCENARIOS: ScenarioDefinition[] = [
  SCENARIO_FIRST_COMMIT,
  SCENARIO_CREATE_BRANCH,
  SCENARIO_MERGE_BRANCH,
  SCENARIO_FIX_MISTAKE,
  SCENARIO_STASH_WORK,
];
